### ISSUE TITLE
UnboundLocalError: local variable 'target' referenced before assignment

### ISSUE THREAD

**Issue by ikarisan** [UncleSocks/onyx-caaat#3]
Hi!

I am trying to connect to my Cisco C1000 switch but without success. 
Every time I try to connect I get the following traceback:

```
$ python3 onyx.py -i

Target > 192.168.200.21
Username > user
Password > ******
Enable # **********
Assessing device 1 out of 1

Connecting to target Cisco router 192.168.200.21 via SSH...
SSH connection established to 192.168.200.21:22
Interactive SSH session established
Traceback (most recent call last):
  File "/home/shinji/develop/onyx/onyx.py", line 141, in <module>
    onyx()
  File "/home/shinji/develop/onyx/onyx.py", line 67, in onyx
    if arguments().type is None and 'type' not in target.get(device_key, {}):
UnboundLocalError: local variable 'target' referenced before assignment
```

(I added a "verbose = True," line to ssh.py to get the SSH messages)

Onyx 2024.1.0
Python 3.10.12
netmiko-4.3.0
paramiko-3.4.0

I had some warnings installing the requirements:

`Discarding https://files.pythonhosted.org/packages/12/bb/f622a8a5e64d46ca83020a761877c0ead19140903c9aaf1431f3c531fdf6/evdev-1.7.1.tar.gz#sha256=0c72c370bda29d857e188d931019c32651a9c1ea977c08c8d939b1ced1637fde (from https://pypi.org/simple/evdev/) (requires-python:>=3.6): Requested unknown from https://files.pythonhosted.org/packages/12/bb/f622a8a5e64d46ca83020a761877c0ead19140903c9aaf1431f3c531fdf6/evdev-1.7.1.tar.gz#sha256=0c72c370bda29d857e188d931019c32651a9c1ea977c08c8d939b1ced1637fde (from pynput->maskpass>=0.3.7->-r requirements.txt (line 1)) has inconsistent name: filename has 'evdev', but metadata has 'unknown'`

and

`Discarding https://files.pythonhosted.org/packages/f3/0c/c87b141250a650ee53d4e9957e905b17c144cda6dc4187cbe89a641a1b34/evdev-1.7.0.tar.gz#sha256=95bd2a1e0c6ce2cd7a2ecc6e6cd9736ff794b3ad5cb54d81d8cbc2e414d0b870 (from https://pypi.org/simple/evdev/) (requires-python:>=3.6): Requested unknown from https://files.pythonhosted.org/packages/f3/0c/c87b141250a650ee53d4e9957e905b17c144cda6dc4187cbe89a641a1b34/evdev-1.7.0.tar.gz#sha256=95bd2a1e0c6ce2cd7a2ecc6e6cd9736ff794b3ad5cb54d81d8cbc2e414d0b870 (from pynput->maskpass>=0.3.7->-r requirements.txt (line 1)) has inconsistent name: filename has 'evdev', but metadata has 'unknown'`

Any ideas?

Thorsten

**Comment by ikarisan** [comment]
onyx is starting if I leave the interactive mode and define my system inside the target.json file. 
But than I encountered a new problem. Although I have given the "-o c100_rerport.html" parameter, the script states "HTML report has been successfully exported as 2024-07-03_18-15-06-t1.html" and the report has been written to the standard target file "report_modules/reports/2024-07-03_18-15-06-t1.html".:(

**Comment by UncleSocks** [comment]
Hey Thorsten,

I'll look into this a bit more later, but you are right. It looks like the issue is being caused by the target.json file or the lack thereof. The script is expecting that "target" variable, which is obtained after parsing the target.json file -- in your case would not exist, throwing you that error.

As for the HTML filename, this is an expected behavior. When running the non-interactive mode, the '-o' option is basically being bypassed and it will automatically create unique HTML filenames (using the datetime.now() and the device key value, which is t1 in your case) to avoid overwrites when assessing multiple routers. 

I will have to modify the script to function even without the target.json file when using interactive mode asap. For now you can either run it in non-interactive mode or try to download the script prior to yesterday's commit (https://github.com/UncleSocks/onyx-caaat-automated-cisco-configuration-assessment-and-auditing-tool/tree/be60a0db2f6844e85f22dd89a305364555729a33). For the latter, the non-interactive mode is not yet available.

Best regards,
Tyrone

**Comment by ikarisan** [comment]
Hi Tyrone,

a taget.json file exists because it is part of your yesterday's commit. ;) 
It seems that there is a problem with "target" when using the interactive mode.
But I can live with it if I have to enter all the information in the targets.json file, because I will have to audit more than one Cisco switch.  :)

**Comment by UncleSocks** [comment]
No worries, Thorsten. :)

Also, I'd like to note that the script was designed to audit Cisco Routers, specifically those that are running IOS 15 and IOS 17. I'm not too sure how it will do in auditing C1000 switches.

**Comment by ikarisan** [comment]
I will report ;) 
But I took a quick look inside the "Cisco IOS 15 (4.1.1)" benchmark und there doesn't seem to be anything in there that wouldn't also work for switches.

**Comment by UncleSocks** [comment]
The issue should now be fixed :)

There was an issue in the if-else statement when checking whether to automatically check for the device type/version.
