### ISSUE TITLE
target.json: unable to change "t1" entry name

### ISSUE THREAD

**Issue by grotewortel** [UncleSocks/onyx-caaat#4]
Hi,

When using target.json with valid target and credentials, when I change:
```
{
    "t1" : {
```

to

```
{
    "t1.awesomescript.com" : {
```

the script does not login to the destination router anymore.

Can you please look at this?

**Comment by UncleSocks** [comment]
Hi Jan,

The 't1' is just a device key to identify multiple devices. It is not meant to be the domain/FQDN of the target device since ONYX cannot resolve it.

If you want to assess n number of devices you will have to add t1, t2, t3, to tn and include the required details as shown in the sample target JSON file.

**Comment by grotewortel** [comment]
Clear. Does it have to follow t1, t2, t3 (+1 each step) ? Or can it be something else? 
If so, what are the naming rules?

I just learning that this is called the device key :-)  and it ends up in the filename.
That makes the value important to get a filename that makes sense.

Thanks!
Jan

**Comment by UncleSocks** [comment]
Yup, for now, it uses t1, t2... tn to identify each device to be assessed.
